import os
from enum import Enum

from db_utils import DbConfig

SERVICE_DATA_AGGREGATOR_DB__DB_URI = os.environ['SERVICE_DATA_AGGREGATOR_DB__DB_URI']
SERVICE_DATA_AGGREGATOR_DB__SYS_USER_ID = os.environ['SERVICE_DATA_AGGREGATOR_DB__SYS_USER_ID']

SERVICE_DATA_AGGREGATOR_DB__SYS__TYPE_ID = os.environ['SERVICE_DATA_AGGREGATOR_DB__SYS__TYPE_ID']

SERVICE_DATA_AGGREGATOR_DB__SYS__MANUFACTURER_ID = os.environ['SERVICE_DATA_AGGREGATOR_DB__SYS__MANUFACTURER_ID']

SERVICE_DATA_AGGREGATOR_DB__SYS__GATEWAY_ID = os.environ['SERVICE_DATA_AGGREGATOR_DB__SYS__GATEWAY_ID']

SERVICE_DATA_AGGREGATOR_DB__SYS__PROTOCOL_ID_SMP = os.environ['SERVICE_DATA_AGGREGATOR_DB__SYS__PROTOCOL_ID_SMP']
SERVICE_DATA_AGGREGATOR_DB__SYS__PROTOCOL_ID_SMP_NCP = os.environ['SERVICE_DATA_AGGREGATOR_DB__SYS__PROTOCOL_ID_SMP_NCP']
SERVICE_DATA_AGGREGATOR_DB__SYS__PROTOCOL_ID_WATER_5 = os.environ['SERVICE_DATA_AGGREGATOR_DB__SYS__PROTOCOL_ID_WATER_5']

SERVICE_DATA_AGGREGATOR_DB__SYS__GATEWAY_NETWORK_ID = os.environ['SERVICE_DATA_AGGREGATOR_DB__SYS__GATEWAY_NETWORK_ID']
SERVICE_DATA_AGGREGATOR_DB__SYS__GATEWAY_NETWORK__SMP_UDP_SERVER__ID = os.environ['SERVICE_DATA_AGGREGATOR_DB__SYS__GATEWAY_NETWORK__SMP_UDP_SERVER__ID']
SERVICE_DATA_AGGREGATOR_DB__SYS__GATEWAY_NETWORK__SMP_NCP_UDP_SERVER__ID = os.environ['SERVICE_DATA_AGGREGATOR_DB__SYS__GATEWAY_NETWORK__SMP_NCP_UDP_SERVER__ID']

NERO_OLD__ENC_KEY_ID = os.environ['NERO_OLD__ENC_KEY_ID']

DEVICE_GATEWAY__NAME = 'GATEWAY'
DEVICE_GATEWAY_NETWORK__NAME__SMP = 'SERVER__UDP__SMP'
DEVICE_GATEWAY_NETWORK__NAME__SMP_NCP = 'SERVER__UDP__SMP_NCP'


DEVICE_GATEWAY__PROTOCOL_SMP = 'SMP'
DEVICE_GATEWAY__PROTOCOL_NCP_SMP = 'NCP_SMP'
DEVICE_GATEWAY__PROTOCOL_WATER_5 = 'WATER_5'

DEVICE_GATEWAY__TYPE_NAMES = ['WATER', 'ELECTRIC', 'OTHER', 'WATER5']
DEVICE_GATEWAY__INTEGRATION_NAMES = ['MTS', 'A1', 'NERO_OLD', 'BECLOUD']

SERVICE_DATA_AGGREGATOR_DB__BATTERY_THRESHOLD = os.environ['SERVICE_DATA_AGGREGATOR_DB__BATTERY_THRESHOLD']

NERO_OLD__AES_KEY = os.environ['NERO_OLD__AES_KEY'].encode()
# TODO:  move to env variables


db_config = DbConfig(uri=SERVICE_DATA_AGGREGATOR_DB__DB_URI)


class IntervalSelectValue(Enum):
    month = '1 month'
    day = '1 day'
    hour = '1 hour'
    half_hour = '30 minute'
